displayName=Karambwan AFK Helper
author=W362
description=A plugin to make afk fishing Karambwans better
tags=karambwan,fishing,afk,karam,bwana
version=1.0
plugins=com.karambwanfishing.KarambwanFishingPlugin
build=standard